-- ============================================================================
-- SecureBank initial schema
-- All money is stored as NUMERIC(19,4) to avoid floating-point rounding errors.
-- ============================================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(34)   NOT NULL UNIQUE,
    owner_id       BIGINT        NOT NULL REFERENCES users (id),
    balance        NUMERIC(19,4) NOT NULL DEFAULT 0,
    currency       VARCHAR(3)    NOT NULL DEFAULT 'USD',
    status         VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    version        BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT chk_balance_non_negative CHECK (balance >= 0)
);

CREATE INDEX idx_accounts_owner ON accounts (owner_id);

CREATE TABLE transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(36)   NOT NULL UNIQUE,
    from_account_id     BIGINT        REFERENCES accounts (id),
    to_account_id       BIGINT        REFERENCES accounts (id),
    amount              NUMERIC(19,4) NOT NULL,
    type                VARCHAR(20)   NOT NULL,
    status              VARCHAR(20)   NOT NULL,
    description         VARCHAR(255),
    created_at          TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT chk_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_tx_from_account ON transactions (from_account_id);
CREATE INDEX idx_tx_to_account   ON transactions (to_account_id);
CREATE INDEX idx_tx_created_at   ON transactions (created_at);

CREATE TABLE audit_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50),
    action     VARCHAR(100) NOT NULL,
    detail     VARCHAR(1000),
    ip_address VARCHAR(45),
    created_at TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_username   ON audit_logs (username);
CREATE INDEX idx_audit_created_at ON audit_logs (created_at);
